import 'server-only'
import { requireAuth, type AuthUser } from './auth.service'

export type AdminPermissionName =
  | 'PRODUCT_CREATE'
  | 'PRODUCT_UPDATE'
  | 'PRODUCT_DELETE'
  | 'PRODUCT_VIEW'
  | 'ORDER_VIEW'
  | 'ORDER_UPDATE'
  | 'ORDER_CANCEL'
  | 'INVENTORY_VIEW'
  | 'INVENTORY_UPDATE'
  | 'INVENTORY_MANAGE'
  | 'INVENTORY_ADJUST'
  | 'CUSTOMER_VIEW'
  | 'CUSTOMER_MANAGE'
  | 'COUPON_MANAGE'
  | 'CONTENT_MANAGE'
  | 'PAYMENT_VIEW'
  | 'AUDIT_VIEW'
  | 'ANALYTICS_VIEW'
  | 'SETTINGS_MANAGE'
  | 'USER_VIEW'
  | 'USER_MANAGE'
  | 'MARKETPLACE_VIEW'
  | 'MARKETPLACE_MANAGE'
  | 'SHIPPING_VIEW'
  | 'SHIPPING_MANAGE'
  | 'SHIPPING_LABEL'
  | 'SHIPPING_CANCEL'
  | 'VIEW_SHIPPING'
  | 'MANAGE_SHIPPING'
  | 'WAREHOUSE_VIEW'
  | 'WAREHOUSE_PICK'
  | 'WAREHOUSE_PACK'
  | 'WAREHOUSE_MANIFEST'
  | 'WAREHOUSE_MANAGE'
  | 'WAREHOUSE_EXCEPTION'
  | 'WAREHOUSE_LOCATION_VIEW'
  | 'WAREHOUSE_LOCATION_MANAGE'
  | 'WAREHOUSE_WAVE_VIEW'
  | 'WAREHOUSE_WAVE_MANAGE'
  | 'WAREHOUSE_RETURN_VIEW'
  | 'WAREHOUSE_RETURN_INSPECT'
  | 'WAREHOUSE_PRINTER_VIEW'
  | 'WAREHOUSE_PRINTER_MANAGE'
  | 'WAREHOUSE_PRINT'
  | 'WAREHOUSE_COUNT_VIEW'
  | 'WAREHOUSE_COUNT_MANAGE'
  | 'WAREHOUSE_COUNT_RECONCILE'
  | 'WAREHOUSE_CARTON_MANAGE'
  | 'PRODUCTION_VIEW'
  | 'PRODUCTION_MANAGE'
  | 'PRODUCT_COST_VIEW'
  | 'PRODUCT_COST_MANAGE'
  | 'PRODUCT_ECONOMICS_VIEW'
  | 'PRODUCT_ECONOMICS_MANAGE'
  | 'MATERIAL_VIEW'
  | 'MATERIAL_MANAGE'

const ROLE_PERMISSIONS: Record<AuthUser['role'], AdminPermissionName[]> = {
  SUPER_ADMIN: [
    'PRODUCT_CREATE',
    'PRODUCT_UPDATE',
    'PRODUCT_DELETE',
    'PRODUCT_VIEW',
    'ORDER_VIEW',
    'ORDER_UPDATE',
    'ORDER_CANCEL',
    'INVENTORY_VIEW',
    'INVENTORY_UPDATE',
    'INVENTORY_MANAGE',
    'INVENTORY_ADJUST',
    'CUSTOMER_VIEW',
    'CUSTOMER_MANAGE',
    'COUPON_MANAGE',
    'CONTENT_MANAGE',
    'PAYMENT_VIEW',
    'AUDIT_VIEW',
    'ANALYTICS_VIEW',
    'SETTINGS_MANAGE',
    'USER_VIEW',
    'USER_MANAGE',
    'MARKETPLACE_VIEW',
    'MARKETPLACE_MANAGE',
    'SHIPPING_VIEW',
    'SHIPPING_MANAGE',
    'SHIPPING_LABEL',
    'SHIPPING_CANCEL',
    'VIEW_SHIPPING',
    'MANAGE_SHIPPING',
    'WAREHOUSE_VIEW',
    'WAREHOUSE_PICK',
    'WAREHOUSE_PACK',
    'WAREHOUSE_MANIFEST',
    'WAREHOUSE_MANAGE',
    'WAREHOUSE_EXCEPTION',
    'WAREHOUSE_LOCATION_VIEW',
    'WAREHOUSE_LOCATION_MANAGE',
    'WAREHOUSE_WAVE_VIEW',
    'WAREHOUSE_WAVE_MANAGE',
    'WAREHOUSE_RETURN_VIEW',
    'WAREHOUSE_RETURN_INSPECT',
    'WAREHOUSE_PRINTER_VIEW',
    'WAREHOUSE_PRINTER_MANAGE',
    'WAREHOUSE_PRINT',
    'WAREHOUSE_COUNT_VIEW',
    'WAREHOUSE_COUNT_MANAGE',
    'WAREHOUSE_COUNT_RECONCILE',
    'WAREHOUSE_CARTON_MANAGE',
    'PRODUCTION_VIEW',
    'PRODUCTION_MANAGE',
    'PRODUCT_COST_VIEW',
    'PRODUCT_COST_MANAGE',
    'PRODUCT_ECONOMICS_VIEW',
    'PRODUCT_ECONOMICS_MANAGE',
    'MATERIAL_VIEW',
    'MATERIAL_MANAGE',
  ],
  ADMIN: [
    'PRODUCT_CREATE',
    'PRODUCT_UPDATE',
    'PRODUCT_DELETE',
    'PRODUCT_VIEW',
    'ORDER_VIEW',
    'ORDER_UPDATE',
    'ORDER_CANCEL',
    'INVENTORY_VIEW',
    'INVENTORY_UPDATE',
    'INVENTORY_MANAGE',
    'INVENTORY_ADJUST',
    'CUSTOMER_VIEW',
    'CUSTOMER_MANAGE',
    'COUPON_MANAGE',
    'CONTENT_MANAGE',
    'PAYMENT_VIEW',
    'AUDIT_VIEW',
    'ANALYTICS_VIEW',
    'SETTINGS_MANAGE',
    'USER_VIEW',
    'USER_MANAGE',
    'MARKETPLACE_VIEW',
    'MARKETPLACE_MANAGE',
    'SHIPPING_VIEW',
    'SHIPPING_MANAGE',
    'SHIPPING_LABEL',
    'SHIPPING_CANCEL',
    'VIEW_SHIPPING',
    'MANAGE_SHIPPING',
    'WAREHOUSE_VIEW',
    'WAREHOUSE_PICK',
    'WAREHOUSE_PACK',
    'WAREHOUSE_MANIFEST',
    'WAREHOUSE_MANAGE',
    'WAREHOUSE_EXCEPTION',
    'WAREHOUSE_LOCATION_VIEW',
    'WAREHOUSE_LOCATION_MANAGE',
    'WAREHOUSE_WAVE_VIEW',
    'WAREHOUSE_WAVE_MANAGE',
    'WAREHOUSE_RETURN_VIEW',
    'WAREHOUSE_RETURN_INSPECT',
    'WAREHOUSE_PRINTER_VIEW',
    'WAREHOUSE_PRINTER_MANAGE',
    'WAREHOUSE_PRINT',
    'WAREHOUSE_COUNT_VIEW',
    'WAREHOUSE_COUNT_MANAGE',
    'WAREHOUSE_COUNT_RECONCILE',
    'WAREHOUSE_CARTON_MANAGE',
    'PRODUCTION_VIEW',
    'PRODUCTION_MANAGE',
    'PRODUCT_COST_VIEW',
    'PRODUCT_COST_MANAGE',
    'PRODUCT_ECONOMICS_VIEW',
    'PRODUCT_ECONOMICS_MANAGE',
    'MATERIAL_VIEW',
    'MATERIAL_MANAGE',
  ],
  ORDER_MANAGER: [
    'ORDER_VIEW',
    'ORDER_UPDATE',
    'ORDER_CANCEL',
    'INVENTORY_VIEW',
    'CUSTOMER_VIEW',
    'PAYMENT_VIEW',
    'SHIPPING_VIEW',
    'SHIPPING_MANAGE',
    'SHIPPING_LABEL',
    'SHIPPING_CANCEL',
    'VIEW_SHIPPING',
    'MANAGE_SHIPPING',
    'WAREHOUSE_VIEW',
    'WAREHOUSE_PICK',
    'WAREHOUSE_PACK',
    'WAREHOUSE_MANIFEST',
    'WAREHOUSE_MANAGE',
    'WAREHOUSE_EXCEPTION',
    'WAREHOUSE_LOCATION_VIEW',
    'WAREHOUSE_LOCATION_MANAGE',
    'WAREHOUSE_WAVE_VIEW',
    'WAREHOUSE_WAVE_MANAGE',
    'WAREHOUSE_RETURN_VIEW',
    'WAREHOUSE_RETURN_INSPECT',
    'WAREHOUSE_PRINTER_VIEW',
    'WAREHOUSE_PRINTER_MANAGE',
    'WAREHOUSE_PRINT',
    'WAREHOUSE_COUNT_VIEW',
    'WAREHOUSE_COUNT_MANAGE',
    'WAREHOUSE_COUNT_RECONCILE',
    'WAREHOUSE_CARTON_MANAGE',
    'PRODUCTION_VIEW',
    'PRODUCT_ECONOMICS_VIEW',
    'MATERIAL_VIEW',
  ],
  CONTENT_MANAGER: [
    'CONTENT_MANAGE',
    'PRODUCT_VIEW',
    'PRODUCT_CREATE',
    'PRODUCT_UPDATE',
  ],
  SUPPORT: [
    'CUSTOMER_VIEW',
    'ORDER_VIEW',
    'PRODUCT_VIEW',
    'SHIPPING_VIEW',
    'VIEW_SHIPPING',
    'WAREHOUSE_VIEW',
    'WAREHOUSE_RETURN_VIEW',
  ],
  STAFF: [
    'PRODUCT_VIEW',
    'ORDER_VIEW',
    'INVENTORY_VIEW',
    'SHIPPING_VIEW',
    'VIEW_SHIPPING',
    'WAREHOUSE_VIEW',
    'WAREHOUSE_PICK',
    'WAREHOUSE_PACK',
    'WAREHOUSE_LOCATION_VIEW',
    'WAREHOUSE_WAVE_VIEW',
    'WAREHOUSE_RETURN_VIEW',
    'WAREHOUSE_PRINT',
    'WAREHOUSE_COUNT_VIEW',
    'PRODUCTION_VIEW',
    'MATERIAL_VIEW',
  ],
  CUSTOMER: [],
}

/**
 * Checks if a specific role possesses a permission
 */
export function hasPermission(
  role: AuthUser['role'],
  permission: AdminPermissionName
): boolean {
  if (role === 'SUPER_ADMIN') return true
  const list = ROLE_PERMISSIONS[role] || []
  return list.includes(permission)
}

/**
 * Guards routes requiring a specific administrative permission
 */
export async function requirePermission(
  request: Request,
  permission: AdminPermissionName
): Promise<AuthUser> {
  const user = await requireAuth(request)

  if (!hasPermission(user.role, permission)) {
    throw new Error(
      `FORBIDDEN: Bu işlem için '${permission}' yetkisi gereklidir. Mevcut rol: ${user.role}`
    )
  }

  return user
}
